### ISSUE TITLE
can i use with uses-sdk:minSdkVersion 15???

### ISSUE THREAD

**Issue by Xcent-xl** [andremion/Floating-Navigation-View#4]

**Comment by andremion** [comment]
Not for now.
It uses [Reveal Animation](https://developer.android.com/reference/android/view/ViewAnimationUtils.html#createCircularReveal) that only works starting API 21.

**Comment by asajadi84** [comment]
I just modified FloatingNavigationView.java to support lower versions of android down to API 15 and Androidx.
Of course without any fancy reveal animations for them, but it works!
[FloatingNavigationView.zip](https://github.com/andremion/Floating-Navigation-View/files/3510939/FloatingNavigationView.zip)

Ps: In order to use this you should create a drawable directory with anydpi-v21 qualifier and move everything from drawable folder to that direction. Then you should use static icons (Or Compat Animated Vector Drawables) for API below 21.

**Comment by andremion** [comment]
Hello guys! Thanks for your interest in this library.
I just released https://github.com/andremion/Floating-Navigation-View/releases/tag/v1.2.0 using minimum SDK version as 19.
I prefer having a solution that doesn't break the animation since that's the propose of the library.
